name: WorldGuard-Advanced
main: WorldGuard\WorldGuard
api: [3.0.0]
version: 1.0
author: Chalapa
website: https://github.com/MihaiChirculete
commands:
  region:
    aliases: ["rg"]
    default: op
permissions:
  worldguard.create:
    default: op
  worldguard.modify:
    default: op
  worldguard.delete:
    default: op
