name: WorldGuard
main: Chalapa13\WorldGuard\WorldGuard
api: [3.0.0]
version: 1.0.3
author: Chalapa
website: https://github.com/Chalapa13
commands:
  region:
    aliases: ["rg"]
    default: op
permissions:
  worldguard.create:
    default: op
  worldguard.modify:
    default: op
  worldguard.delete:
    default: op
  worldguard.enter:
    default: op
  worldguard.leave:
    default: op
  worldguard.build:
    default: op
  worldguard.break:
    default: op
  worldguard.edit:
    default: op
  worldguard.eat:
    default: op
  worldguard.drop:
    default: op
  worldguard.usechest:
    default: op
  worldguard.usechestender:
    default: op
  worldguard.enchantingtable:
    default: op
  worldguard.usedoors:
    default: op
  worldguard.usegates:
    default: op
  worldguard.usetrapdoors:
    default: op
  worldguard.usefurnaces:
    default: op
  worldguard.useanvil:
    default: op
  worldguard.usecauldron:
    default: op
  worldguard.usebrewingstand:
    default: op